# Konfigurasyon ng LightLogin Plugin.
# Ang seryeng ito ay ginagamit upang lubos na baguhin ang mga mahahalagang bahagi ng software na ito.
#
# bersyon 1.0.0 (HUWAG BAGUHIN)
# !MANGYARING BANTAYAN NG MAAYOS!
plugin:
  info:
    - "{PREFIX}: &6Impormasyon ng Plugin"
    - "&eAng plugin na ito ay kasalukuyang nasa bersyon {VERSION}"
    - "&eAng developer ng software na ito ay si CMarco"
    - "&7Ang plugin na ito ay ginawa noong Ene. 2024 upang protektahan ang iyong server at gawing ligtas para sa lahat!"

# Konfigurasyon ng Database
database:
  type: "SQLITE"       # Uri ng Database (Alternatibo: SQLITE, MYSQL, POSTGRESQL)
  username: "root"      # Username ng iyong database account
  password: "password"  # Password ng iyong database account
  address: "127.0.0.1"  # Address ng koneksyon
  port: 3306            # Port ng koneksyon
  db-name: "local"      # Pangalan ng database para sa koneksyon at pagsasave ng data.

# Ugali ng Server matapos ang mga crash o isyu sa database
crash-shutdown: false   # Ipatay ang server matapos ang matinding crash o mga isyu sa database.

void-world:
  enabled: false
  mode: 'NORMAL'        # NORMAL \ THE_END

login-blindness:       # Paganahin ang kahangalang sa panahon ng login o pagsusuri.
  enabled: false

# Konfigurasyon ng Login
login:
  command-delay: 3       # Pagitan ng segundo bago maging epektibo ang login command
  kick-after-seconds: 120
  max-failed-attempts: 10 # Pinakamataas na pinapayagang mabigong login attempts bago magkaruon ng parusa
  bruteforce-punishment: # Mga command para sa parusang bruteforce attempts
    - "clear {PLAYER}"
    - "tempban {PLAYER} 1h &cIkaw ay masyadong madalas na mabigong mag-login!"
  auto-login: true        # Awtomatikong mag-login ang mga players pagkatapos ng pagrehistro
  session-expire: 900     # Oras sa segundo bago mag-expire ang login session (default na 15 minuto)
  allowed-commands:       # Listahan ng mga command na maaring gawin ng mga players bago mag-login
    - "/help"
    - "/login"
    - "/register"

safety:
  players-same-ip: 2      # Ilang players ang maaring mag-connect sabay-sabay gamit ang parehong IPv4?

# Konfigurasyon ng Safe Passwords
safe-passwords:
  force-safe:
    enabled: true         # I-enable o I-disable ang forced safe password feature
    min-length: 8         # Minimum na haba ng password
    min-uppercase: 1      # Minimum na bilang ng mga uppercase characters
    min-numbers: 2        # Minimum na bilang ng mga numeric characters
    min-special: 1        # Minimum na bilang ng mga special characters
    allowed-special: ['@', '^', '-', '_', '#', '!', '?', '*', '$', '%', '&', '*'] # Mga allowed na special characters

# Konfigurasyon ng Email
email:
  enabled: false
  email-smtp: 'smtp.gmail.com'                    # Ang nagbibigay ng SMTP server.
  email-port: 465                                 # Ang port na ginagamit ng SMTP server.
  use-tls: true                                   # Gamitin ang TLS secure connection.
  email-account: ''                               # Ang iyong email account (hal. jeb@mojang.com).
  email-password: ''                              # Ang password na kaugnay sa iyong email account.
  email-sender-name: 'LightLogin'                 # Ang pangalan ng nagpapadala ng email.
  recovery-password-min-length: 8                 # Haba ng awtomatikong ginagawang password.
  recovery-min-delay: 90                          # Ang minimum na mga minuto sa pagitan ng bawat request na pag-reset.
  email-subject: 'Ang iyong bagong LightLogin password!'  # Paksa ng recovery email.
  email-text-content:                             # Nilalaman ng email,
    # Mga pook marka: {PASSWORD}, {PLAYER}
    - "Mahal na {PLAYER},"
    - "Ito ang bagong pansamantalang password na iyong hinihiling mula sa server:"
    - "Password: {PASSWORD}"
    - "Mangyaring huwag itong ibahagi at huwag mag-atubiling baguhin ito mamaya."
    - ""
    - "~ Aking Minecraft Server"

# I-configure ang tunog sa yugto ng pag-login
# Mangyaring tingnan ang mga pangalan ng sounds sa Bukkit API ayon sa itinakda ng iyong bersyon,
# Maaari mong mahanap ang isang listahan ng mga ito dito (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html)
sounds:
  enabled: true
  successful-login: 'BLOCK_NOTE_BLOCK_HARP'   # Ang tunog na i-play pagkatapos mag-login.
  wrong-password: 'ENTITY_VILLAGER_HURT'      # Ang tunog na i-play kapag mali ang password ng gumagamit.
  action-bar-tick: 'BLOCK_LEVER_CLICK'        # Ang tunog na i-play para sa tampok ng oras ng action bar.

# Animation ng Natitirang Oras ng Pag-login
# Ang feature na ito ay nagpapagana ng isang animation na nagpapakita kung gaano katagal pa ang natitirang oras ng player upang mag-authenticate.
login-animation:
  enabled: true
  display-type: 'ACTION_BAR'                          # Mga available na pagpipilian: 'TITLE' o 'ACTION_BAR'.
  format: "&7[{BAR}&7] &e Natitirang Oras ng Pag-login &c{TIME}"   # Ang format ng teksto na ginagamit.
  bar-length: 24                                      # Ang haba ng ginagawang bar.
  bar-character-passed: '|'                           # Ang karakter na ginagamit upang magtakda ng oras na lumipas.
  bar-character-not-passed: '|'                       # Ang karakter na ginagamit upang hindi lumipas ang oras.
  bar-time-passed-colour: '&c'                        # Ang kulay na ginagamit para sa oras na lumipas na.
  bar-time-not-passed-colour: '&a'                    # Ang kulay na ginagamit para sa oras na hindi pa lumilipas.

# Konfigurasyon ng Mensahe
messages:
  prefix: "&7╓&eLightLogin&7╛&f" # Prefix para sa mga mensaheng ng plugin
  player-only-command: ["{PREFIX}: &cAng command na ito ay maaring gawin lamang ng player!"]
  missing-permission: ["{PREFIX}: &cKulang ang iyong pahintulot &l{PERMISSION}"]
  incorrect-command-usage: ["{PREFIX}: &cMali ang paggamit ng command na ito!"]
  register-message:
    - "{PREFIX}: &cMangyaring magrehistro gamit ang command:"
    - "{PREFIX}: &e/register <psw> <psw>"
  register-incorrect-usage:
    - "{PREFIX}: &cMaling paggamit ng register command!"
    - "{PREFIX}: &cGamitin ang &e/register <password> <password>"
  register-unequal-passwords:
    - "{PREFIX}: &cMaling password na isinulat!"
    - "{PREFIX}: &cAng dalawang password ay hindi magkapareho."
  register-error:
    - "{PREFIX}: &cMay nangyaring mali habang nagre-register"
  register-success:
    - "{PREFIX}: &aMatagumpay kang nagrehistro :)"
    - "{PREFIX} &aSiguruhing panatilihing &lligtas ang iyong mga password"
  already-registered:
    - "{PREFIX}: &cIkaw ay mayroon nang account!"
    - "{PREFIX}: &cGumamit ng &e/changepassword <oldPassword> <newPassword>"
    - "{PREFIX}: &ckung gusto mong palitan ang iyong kasalukuyang password!"
  unregistered:
    - "{PREFIX}: &cMay ibang tao na nag-unregister sa iyo!"
    - "{PREFIX}: &cMagrehistro ulit gamit ang /register <password> <password>"
  unregistered-success:
    - "{PREFIX}: &aMatagumpay na nai-unregister ang player na ito."
  unsafe-password:
    - "{PREFIX}: &cAng iyong password ay hindi ligtas!"
    - "{PREFIX}: &cIto ay dapat na tumugma sa sumusunod na kundisyon:"
    - "&7- &cHindi bababa sa &e{MIN_LENGTH} &ccharacters"
    - "&7- &cHindi bababa sa &e{MIN_UPCASE} &cmga uppercase, &e{MIN_SPECIAL} &cmga special characters, &e{MIN_NUMBERS} &cmga numero."
    - "&7- &cAllowed na special chars: {SPECIAL}"
  command-too-fast:
    - "{PREFIX}: &cMasyado kang mabilis gumamit ng command na ito!"
  login-already-authenticated:
    - "{PREFIX}: &cIkaw ay nakalogin na!"
  login-took-too-much-time:
    - "{PREFIX}: &4INITSE!"
    - "&cMatagal kang nagtagal sa pag-authenticate."
  login-error:
    - "{PREFIX}: &cMay nangyaring mali habang nag-login."
  login-incorrect-usage:
    - "{PREFIX}: &cMaling paggamit ng login command!"
    - "{PREFIX}: &cGamitin ang &e/login <password>"
  login-success:
    - "{PREFIX}: &aMatagumpay kang nag-login."
  login-auto:
    - "{PREFIX}: &aIkaw ay awtomatikong na-authenticate."
  login-messages:
    - "{PREFIX}: &cMangyaring mag-login gamit ang command:"
    - "{PREFIX}: &e/login <password>"
  login-unregistered:
    - "{PREFIX}: &cHindi ka makapag-login nang walang pagkakarehistro!"
  login-wrong-password:
    - "{PREFIX}: &cMaling password sa login!"
  unregister-incorrect-usage:
    - "{PREFIX}: &cMaling paggamit ng unregister command!"
    - "{PREFIX}: &cGamitin ang &e/unregister <player>"
  unregister-not-found:
    - "{PREFIX}: &cWalang nahanap na player na rehistrado sa ganitong pangalan."
  changepassword-unregistered:
    - "{PREFIX}: &cHindi mo mababago ang iyong password nang hindi nakarehistro."
  changepassword-wrong-oldpassword:
    - "{PREFIX}: &cMali ang iyong lumang password!"
  changepassword-changed:
    - "{PREFIX}: &aMatagumpay na na-update ang iyong lumang password!"
  player-not-online:
    - "{PREFIX}: &aHindi online ang player na iyan!"
  players-same-ip: "{PREFIX}: &cMasyadong maraming players ang konektado mula sa iyong network address!" # isa lamang na string ang pinapayagan!
  password-in-chat:
    - "{PREFIX}: &c&lBABALA"
    - "&7» &4Isinulat mo ang iyong password sa chat,"
    - "&7» &4Ang iyong mensahe ay kanselado, mag-ingat ka!"
  email-update-help:
    - "{PREFIX}: &eTulong sa Email"
    - "&7Itakda ang iyong recovery email gamit ang:"
    - "&7/&eemail &7<&emyEmail&7>"
  email-invalid-format:
    - "{PREFIX}: &cMay maling format ang email na ito!"
  email-updated:
    - "{PREFIX}: &aAng iyong bagong email ay na-set sa &e{EMAIL}"
  email-something-wrong:
    - "{PREFIX}: &cMay nangyaring hindi tama habang ini-update ang iyong email."
  password-reset-help:
    - "{PREFIX}: &eTulong sa Pag-reset ng Password"
    - "&7I-reset ang iyong password gamit ang:"
    - "&7/&eresetpassword"
  password-reset-help-admins:
    - "{PREFIX}: &eTulong sa Pag-reset ng Password para sa Admins"
    - "&7I-reset ang password ng anumang player gamit ang:"
    - "&7/&eresetpassword &7<&6player&7>"
  password-reset-missing-email:
    - "{PREFIX}: &cHindi namin ma-reset ang password"
    - "&cdahil walang kaugnayang email na naka-associate!"
  password-reset-not-enabled:
    - "{PREFIX}: &cHindi pa na-set up ang Email Password Recovery"
    - "&cng mga administrator ng server na ito."
  password-reset-failed:
    - "{PREFIX}: &cMay nangyaring mali habang inii-reset ang password ni &e{PLAYER}&c."
  password-reset-success:
    - "{PREFIX}: &aMatagumpay nating naipadala ang reset email kay &e{EMAIL}."
  password-reset-too-early:
    - "{PREFIX}: &cKailangan mong maghintay ng mas mahabang oras bago ka makapag-request ng bagong pag-reset ng password."

